core:
  - changed-files:
      - any-glob-to-any-file: "crates/zenii-core/**"

frontend:
  - changed-files:
      - any-glob-to-any-file: "web/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"

cli:
  - changed-files:
      - any-glob-to-any-file: "crates/zenii-cli/**"

desktop:
  - changed-files:
      - any-glob-to-any-file: "crates/zenii-desktop/**"
